#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Make one patch from the linux/ source files, for Buildroot.

All files under linux/ (not linux/patches/) are new to the kernel.  Each file
becomes a /dev/null hunk in one generated patch.  The manual patches next to
it change existing kernel files.  Together they are the full change set, so
BR2_LINUX_KERNEL_PATCH can build a stock kernel release.
"""
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OVERLAY = REPO / "linux"
OUTPUT = OVERLAY / "patches" / "0000-esp32s31-add-source-files.patch"

EXCLUDED = {"patches"}

# The loader and the kernel both use the Wi-Fi ABI header.  shared/ has the master copy.
EXTRA = {
    REPO / "shared" / "esp32s31-wifi-ipc.h":
        "drivers/net/wireless/espressif/esp32s31-wifi-ipc.h",
}

HEADER = """\
ESP32-S31: add the SoC's kernel source files

Generated by scripts/mkkernelpatches.py -- do not edit.  Change the files
under linux/ and regenerate with "make kernel-patches".

Signed-off-by: Marco Mueller <hello@annoyedmilk.ch>
---
"""


def excluded(rel):
    return any(rel == e or rel.startswith(e + "/") for e in EXCLUDED)


def hunk(rel, text):
    lines = text.split("\n")
    trailing_newline = lines[-1] == ""
    if trailing_newline:
        lines.pop()
    out = [
        "diff --git a/%s b/%s" % (rel, rel),
        "new file mode 100644",
        "--- /dev/null",
        "+++ b/%s" % rel,
        "@@ -0,0 +1,%d @@" % len(lines),
    ]
    out += ["+" + line for line in lines]
    if not trailing_newline:
        out.append("\\ No newline at end of file")
    return "\n".join(out) + "\n"


def main():
    sources = {}
    for path in sorted(OVERLAY.rglob("*")):
        # Skip macOS metadata such as .DS_Store and ._* files.
        if not path.is_file() or path.name.startswith("."):
            continue
        rel = path.relative_to(OVERLAY).as_posix()
        if excluded(rel):
            continue
        sources[rel] = path
    for path, rel in EXTRA.items():
        sources[rel] = path

    if not sources:
        sys.exit("no overlay sources found under %s" % OVERLAY)

    body = HEADER
    for rel in sorted(sources):
        body += hunk(rel, sources[rel].read_text())
    OUTPUT.write_text(body)
    print("%s: %d files" % (OUTPUT.relative_to(REPO), len(sources)))


if __name__ == "__main__":
    main()
